# Generated by Django 5.2.7 on 2025-10-20 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('markets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market_app.market')),
                ('sellers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market_app.seller')),
            ],
        ),
    ]
