# Generated by Django 5.2.7 on 2025-10-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='markets',
            new_name='market',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sellers',
            new_name='seller',
        ),
    ]
